version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    # should be exposed to the host machine if you want to access it from outside the container localhost:27017
    ports:
      - 27017:27017
    networks:
      - network-backend

networks:
  network-backend:

volumes:
  mongodb_data:
